import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from 'react';
import { useGameStore } from '@/state/gameStore';
export function Hud() {
    const player = useGameStore((state) => state.player);
    const prompt = useGameStore((state) => state.ui.prompt);
    const hpPercent = useMemo(() => Math.max(0, Math.min(100, (player.hp / player.maxHp) * 100)), [player.hp, player.maxHp]);
    const xpPercent = useMemo(() => Math.max(0, Math.min(100, (player.xp / player.maxXp) * 100)), [player.xp, player.maxXp]);
    return (_jsxs("div", { className: "hud", children: [_jsxs("div", { className: "hud-panel hud-top-left", children: [_jsx("div", { className: "hud-title", children: "Adventurer" }), _jsxs("div", { className: "hud-row", style: { marginBottom: '10px' }, children: [_jsx("strong", { children: player.name }), _jsxs("span", { className: "muted", children: ["Level ", player.level] })] }), _jsx("div", { className: "hud-title", children: "HP" }), _jsx("div", { className: "bar", "aria-label": "Health", children: _jsx("div", { className: "bar-fill hp", style: { width: `${hpPercent}%` } }) }), _jsxs("div", { className: "hud-row", style: { marginTop: '8px' }, children: [_jsxs("span", { children: [player.hp, " / ", player.maxHp] }), _jsx("span", { className: "muted", children: "Forest HP" })] }), _jsx("div", { className: "hud-title", style: { marginTop: '14px' }, children: "XP" }), _jsx("div", { className: "bar", "aria-label": "Experience", children: _jsx("div", { className: "bar-fill xp", style: { width: `${xpPercent}%` } }) }), _jsxs("div", { className: "hud-row", style: { marginTop: '8px' }, children: [_jsxs("span", { children: [player.xp, " / ", player.maxXp] }), _jsx("span", { className: "muted", children: "Progress" })] })] }), _jsxs("div", { className: "hud-panel hud-top-right", children: [_jsx("div", { className: "hud-title", children: "Gold" }), _jsx("div", { style: { fontSize: '1.8rem', color: '#fff0bc', fontWeight: 800 }, children: player.gold })] }), _jsxs("div", { className: "hud-panel hud-bottom-right", children: [_jsx("div", { className: "hud-title", children: "Controls" }), _jsxs("div", { className: "controls-list", children: [_jsx("div", { children: "A / Left Arrow - Move Left" }), _jsx("div", { children: "D / Right Arrow - Move Right" }), _jsx("div", { children: "SPACE - Jump" }), _jsx("div", { children: "X - Attack" }), _jsx("div", { children: "E - Interact" })] }), prompt ? _jsx("div", { style: { marginTop: '12px', color: '#fff7d5' }, children: prompt }) : null] })] }));
}
